"""add job table

Revision ID: 3be1f97995b0
Revises: cecd3561b30b
Create Date: 2026-07-14 12:12:19.985148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "3be1f97995b0"
down_revision: Union[str, Sequence[str], None] = "cecd3561b30b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ledger_entry_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledgerentry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
