"""add needs_review and review_reason as ledgerentry columns

Revision ID: 53dd87d9a3f7
Revises:
Create Date: 2026-07-13 10:02:47.507104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "53dd87d9a3f7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ledgerentry", sa.Column("needs_review", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "ledgerentry",
        sa.Column("review_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_ledgerentry_needs_review"),
        "ledgerentry",
        ["needs_review"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ledgerentry_needs_review"), table_name="ledgerentry")
    op.drop_column("ledgerentry", "review_reason")
    op.drop_column("ledgerentry", "needs_review")
    # ### end Alembic commands ###
