"""move job/ledgerentry FK to ledgerentry.job_id

Revision ID: 783bab6594fd
Revises: c2af8cb7a9ec
Create Date: 2026-07-15 13:39:36.640464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "783bab6594fd"
down_revision: Union[str, Sequence[str], None] = "c2af8cb7a9ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("job_ledger_entry_id_fkey"), "job", type_="foreignkey")
    op.drop_column("job", "ledger_entry_id")
    op.add_column("ledgerentry", sa.Column("job_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "ledgerentry", "job", ["job_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ledgerentry", type_="foreignkey")
    op.drop_column("ledgerentry", "job_id")
    op.add_column(
        "job",
        sa.Column("ledger_entry_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("job_ledger_entry_id_fkey"),
        "job",
        "ledgerentry",
        ["ledger_entry_id"],
        ["id"],
    )
    # ### end Alembic commands ###
