"""add job file_key column

Revision ID: c2af8cb7a9ec
Revises: 3be1f97995b0
Create Date: 2026-07-14 13:04:13.551762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "c2af8cb7a9ec"
down_revision: Union[str, Sequence[str], None] = "3be1f97995b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job", sa.Column("file_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "file_key")
    # ### end Alembic commands ###
