"""make review_reason nullable

Revision ID: cecd3561b30b
Revises: 53dd87d9a3f7
Create Date: 2026-07-13 10:34:28.320072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "cecd3561b30b"
down_revision: Union[str, Sequence[str], None] = "53dd87d9a3f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ledgerentry", "review_reason", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ledgerentry", "review_reason", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
